[project]
name = "telescope-network"
version = "0.1.0"
description = "Deployment for Telescope KOI network"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "koi-net-coordinator-node>=0.1.0",
    "koi-net-obsidian-manager-node>=0.1.0",
    "koi-net-slack-telescope-node>=0.1.0",
]
